version: '3'

services:
  php:
    build: .
    volumes:
     - ./src:/var/www/html
    ports:
     - '8000:8000'
  mysql:
    platform: linux/amd64 #M1Macはこれを追加しないと動かない
    image: mysql:8.0.33
    container_name: laravel_project-mysql-1
    ports: 
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: hiromu
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'